### ISSUE TITLE
[FR] Add seed argument to graphplot

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GraphRecipes.jl#110]
I am trying to animate a graph whose node colors change over time. It is exceptionally difficult if I don't use `:circular` as method, because a random layout is created each time.

Is it possible to allow a `seed` argument which seeds the random number generator that creates the graph? So I can give the same `seed` every time I update the plot?

**Comment by JackDevine** [comment]
Does doing `Random.seed!(42)` in your update loop not work?

The `:spectral` method is another method that is deterministic, but I don't really like a lot of the layouts that it produces.

Another fix for this would be to make some layout methods that actually converge properly.

**Comment by Datseris** [comment]
lol, I feel kind of stupid :P yes, this seems to work for me. But let's keep this open, because I feel this should be mentioned in the docs, at the `method` attribute.

**Comment by JackDevine** [comment]
> I feel kind of stupid :P

Haha lol, we are all allowed at least 3 moments like that per day.

The rather global nature of random seeds feels a little unjulian, so I agree that there should be some documentation around this issue. I personally feel that you are best placed to write the documentation, since you only recently learned of the solution. Feel free to add the documentation and close this issue when you are ready.

**Comment by Datseris** [comment]
Sure, but you have to tell me _where_ I find this documentation. I believed that the table in Plots.jl that lists all attributes of `graphplot` is autogenerated. But where is its source?

**Comment by JackDevine** [comment]
Yeah, it is a little tricky to find. It is in https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl

**Comment by Datseris** [comment]
This is too hard for me to read and definitely not worth the time investment understanding something so complicated to add 1 sentence of docs.

Given that you can just add this information immediately. I'd strongly recommend that you do it instead of me.

**Comment by JackDevine** [comment]
No problem, will do.

**Comment by JackDevine** [comment]
Just in case you do get some more time to understand the PlotDocs structure and if you do want to make contributions when you get time:

The attributes were refactored into DataFrames in this PR:
https://github.com/JuliaPlots/PlotDocs.jl/pull/164

The GraphRecipes attribute DataFrame is at line 260 of the file I linked above.

I wasn't actually aware of the changes until after they merged, so I didn't review. I wasn't privy to the original motivation, although looking at it from a high level, I think that the above PR is a big improvement. There were quite a lot of changes including automatic generation of GraphRecipes examples. Having the attributes as a table opens the door to being able to having the aliases being automatically loaded from `GraphRecipes.graph_aliases`. I agree that it is a little more complicated than just manually creating a markdown table, but I think that the extra overhead is worth it.
