### ISSUE TITLE
Add GraphRecipes to `LightGraphs` docs

### ISSUE THREAD

**Issue by keorn** [JuliaPlots/GraphRecipes.jl#111]
Not sure if better placed here or on `LightGraphs` repo.

I think a lot of people look for graph drawing libraries when using other graph libraries, it would be good to include `GraphRecipes` where relevant, like: https://juliagraphs.github.io/LightGraphs.jl/latest/plotting/

**Comment by JackDevine** [comment]
Agreed, I actually thought that it was already on the LightGraphs docs, but I must have been thinking of something else.

I think that the easier we make it to get people up and running, the better.

**Comment by congUoM** [comment]
https://juliagraphs.github.io/LightGraphs.jl/latest/plotting/ seems to mention GraphRecipes now. I have added another example of using GraphRecipes in this mentioning:
https://github.com/congUoM/LightGraphs.jl/blob/master/docs/src/plotting.md

Also, the "ecosystem" part of PlotDocs.jl documentation misses the description of GraphRecipes. So, I have added the description of GraphRecipes into the ecosystem overview of PlotDocs.jl:
https://github.com/congUoM/PlotDocs.jl/blob/master/docs/src/ecosystem.md
