### ISSUE TITLE
Possible missing import or `Plots.jl` dependency

### ISSUE THREAD

**Issue by lmondada** [JuliaPlots/GraphRecipes.jl#165]
Hi everyone,

Issue description
-----------------

If I `] add GraphRecipes` in a new environment, and then run a simple example
```julia
using GraphRecipes
g = [0 1 1; 1 0 1; 1 1 0]
graphplot(g)
```
I get the following error
```
ERROR: MethodError: no method matching plot(::GraphRecipes.GraphPlot)
```

Possible fix
-----------
`] add Plots` and `using Plots` fixes this. So fixing this should be as simple as adding a dependency, or maybe there is a missing import somewhere. Or maybe I am just using the package wrong. Let me know what you think the simplest fix would be. Happy to submit a PR if that helps.

Cheers!
Luca

**Comment by BeastyBlacksmith** [comment]
Seems this should be documented more clearly. So `GraphRecipes` is a collection of `Plots.jl` recipes.
Thats why it should only used in conjunction with `Plots.jl`.

**Comment by lmondada** [comment]
Ok, that makes sense. I agree that writing that explicitly in the docs would solve this. But can I ask: what's the rationale for not having `Plots.jl` as a dependency?

**Comment by JackDevine** [comment]
> Ok, that makes sense. I agree that writing that explicitly in the docs would solve this.

The readme has `using Plots` in it. Of course, if you see any examples in the docs where `using Plots` is not obvious, then feel free to update those docs.

> what's the rationale for not having Plots.jl as a dependency?

The idea of plot recipes is to provide plotting as an optional dependancy. For example, in DifferentialEquations.jl you can pass the solution of a differential equation to `plot` and it will give you a nice plot of the solution. Most users of DifferentialEquations.jl wont actually use this feature, so they shouldn't have to download Plots.jl. For the users that do want to use the DifferentialEquations.jl plot recipe, all they have to do is `using Plots` and they are good to go. Both types of user just have to download (the rather light weight) PlotsRecipes code.

Another reason that plot recipes don't explicitly depend on Plots.jl is that they are designed to be consumed by different "engines". In principle, it could be possible for different plotting engines to render the recipes defined in PlotRecipes.jl. All that they would have to do is overload some methods of `plot` as defined in PlotRecipes. I think that there was some talk of Makie being able to work with plot recipes, therefore linking the Plots.jl and Makie.jl ecosystems. From what I can see, Makie has moved in a different direction to Plots.jl and the two ecosystems are separate for now. Having said that, things move quite fast and I could be out of date.

**Comment by BeastyBlacksmith** [comment]
What could help here is https://github.com/JuliaPlots/RecipesBase.jl/issues/79, otherwise I'd say this is expected behaviour.
