### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by TorkelE** [JuliaPlots/GraphRecipes.jl#187]
When I try to go to the package documentation via the main GitHub page, I click on a link: https://docs.juliaplots.org/stable/graphrecipes/introduction/
However, that page seems to be broken.

**Comment by t-bltg** [comment]
Thanks, fixed by https://github.com/JuliaPlots/GraphRecipes.jl/commit/57a95ad37e8605548b38f6d9eab6aee838859515.

**Comment by louisarhodes** [comment]
Uhhh I don't think it is working...

**Comment by t-bltg** [comment]
I think it is. What link is broken ?

**Comment by louisarhodes** [comment]
This one from above: https://docs.juliaplots.org/stable/graphrecipes/introduction/
Gets a 404 file not found error
