### ISSUE TITLE
Get rid of the Plots dependency

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/GraphRecipes.jl#20]
The plots dependency makes it so that way packages cannot come "preset" with these plot recipes. I think it would be best to kick the Plots.jl dependency here, or at least split this library to have a separate library of recipes which don't need the Plots.jl dependency.

**Comment by mkborregaard** [comment]
Currently, every single recipe in PlotRecipes depends on Plots, via the @userplot macro. I have thought myself of the idea of having a library of recipes that don't depend on Plots, but I am not sure about the use cases - can you say more?

**Comment by ChrisRackauckas** [comment]
The precompilation problems. It's due to the fact that you `@eval` in a module after it's precompiled. That doesn't actually update the precompilation files. But then if a module has a dependency on Plots.jl, its precompilation file doesn't update either when Plots.jl evals into its scope. Plots.jl will generally work fine like this (although it's undefined behavior) because the `@eval` will have changed itself in its own scope. But the compiled code of dependent packages will not have updated, and thus will not see any the changes when backends are added. Needless to say... that makes packages which depend on Plots.jl very wonky. In fact, I would go as far as to say that it essentially doesn't work, as can be seen by how both ApproxFun.jl and DifferentialEquations.jl are just completely incompatible with Plots.jl's precompilation (there must be other examples out there too):

https://github.com/JuliaApproximation/ApproxFun.jl/issues/453
https://github.com/JuliaApproximation/ApproxFun.jl/issues/455
https://github.com/JuliaApproximation/ApproxFun.jl/issues/457
https://github.com/JuliaPlots/Plots.jl/issues/545
https://github.com/JuliaPlots/Plots.jl/issues/534
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/105
https://github.com/JuliaPlots/Plots.jl/issues/543

I discussed some of this with TK early on:

https://github.com/JuliaLang/METADATA.jl/pull/5761
https://github.com/JuliaLang/METADATA.jl/pull/5765

That explains essentially what must be happening. It got worse in v0.5 for some reason, probably the compiling of anonymous functions.

Anyways, it makes it so that way larger libraries cannot depend on the recipes here. But can't userplots use `@recipe` and manually define the type they use to dispatch, all without a Plots.jl dependency? I would think this would be the way to go to get around this issue.

**Comment by BeastyBlacksmith** [comment]
Resolved by creating RecipesBase

**Comment by mkborregaard** [comment]
Well that wasn't what resolved it :-) It was resolved by a major refactor at the last VizCon - but you are right the issue can be closed.
