### ISSUE TITLE
Possible documentation improvements

### ISSUE THREAD

**Issue by JackDevine** [JuliaPlots/GraphRecipes.jl#59]
Personally, I believe that GraphRecipes deserves documentation supported by Documenter.jl.

At the very least, the README should include some mention to all of the kwargs available. I was able to find that you could send arguments to the layout method as a dict through the `layout_kw` argument. I only found that out by reading source code, luckily the source code is well written so it wasn't too hard ;)

Maybe this is documented somewhere, but I just couldn't find it. My overarching point is that the documentation could do with some loving. I am willing to put in the work to fix this problem as long as people support the general direction.

**Comment by mkborregaard** [comment]
I agree - one way could be to document it as it's own page in docs.juliaplots.org , the same could be done for StatsPlots - that was actually always the intention.
A PR that would test the code in the readme that already exists, regenerate the images, then PR it all to it's own page in PlotDocs.jl, would accomplish this fairly easily.

**Comment by jjstickel** [comment]
At a minimum, please add a docstring so that `?graphplot` shows something useful.

**Comment by JackDevine** [comment]
Closed by #112
