### ISSUE TITLE
Add aliases for kwargs

### ISSUE THREAD

**Issue by JackDevine** [JuliaPlots/GraphRecipes.jl#77]
I want to add aliases for the keyword arguments, but I don't know how to add aliases for recipes. Does anyone know how to do this?

**Comment by ericphanson** [comment]
I’m not very familiar with recipes, but can this be done by seeing if the old keyword argument is defined, and if so, set the new one to that value? E.g. something similar to this line: https://github.com/JuliaPlots/GraphRecipes.jl/blob/a544318e743c95178f56da84372315fe6cb7541f/src/graphs.jl#L639 

In other words, set the `nodesize` to the current value of the`markersize` via `—->` so it will be overruled by the user input.

**Comment by JackDevine** [comment]
That works! Now I can make the `marker*` problem a little less breaking. I also wanted to make a few other API fixes too.

Thanks for your help. If nobody gets back to us soon on #80 , then we can merge it ourselves. Having read your explanation there, I am quite sure that #80 is mergeable. I would just like to have input from the others if that is possible.

**Comment by ericphanson** [comment]
Great, glad it works ok! Ok, sounds good regarding #80. Thanks for the speedy review over there :).
