### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JackDevine** [JuliaPlots/GraphRecipes.jl#87]
A lot has happened on master since v0.4.0 and some of it is slightly breaking, so we should definitely make a new release.

Summary of changes made:
* Each edge has its own series: #57 
* Edge labels can be specified through the `edgelabel` kwarg #65 
* Directed graphs can now be handled and have arrows #67 
* Nodes are no longer Plots.jl markers. Meaning that `markershape` and `markersize` are now replaced with `nodeshape` and `nodesize` #67 
* Graphs with self edges can be visualized #68 
* Mulitgraphs can be visualized and `edgelabels` accepts triples to specify the labels  #71
* Many of the keyword arguments to `grahplot` have aliases #88

Issues to be fixed before new release:

- [x] #82 
- [x] #56 
- [x] #77 
- [x] #69

I may add to the list and I am open for suggestions to add to the list. I believe that the fact that we have moved away from Plots.jl markers warrants a major release (upgrade to v0.5.0). Fixing #77 will slightly improve things, however, ultimately, we have made a break from the old GraphRecipes in #67.

~~In the meantime, the README gives incorrect results for people who are not on master (see #83). I guess that nobody expected the new release to take this long. Perhaps we should put a warning on the readme? Not sure.~~ EDIT: Fixed in #88

**Comment by mkborregaard** [comment]
This is awesome. Makes sense to put a small ("note: this currently requires the master branch") in the readme. I definitely agree we should push a 0.5.0 versino

**Comment by NHDaly** [comment]
Looking forward to a new release here! :) <3

Since all the cited Issues have been fixed, is there anything else remaining to be done before a release can be tagged?
Thanks!

**Comment by mkborregaard** [comment]
Agreed - I prefer to let @JackDevine do the honors though if you've got the time?

**Comment by JackDevine** [comment]
I have been struggling to find a good time to do this. Fingers crossed I should be able to do it tomorrow evening (New Zealand time).

Thanks for the kind words everyone! :)

**Comment by JackDevine** [comment]
@JuliaRegistrator register

**Comment by JackDevine** [comment]
The tagbot was clever enough to notice a certain lack of upper bounds. I think that I have solved the problem now. In any case, we probably need a better solution than just manually entering upper bounds in the Project.toml. I think that the CompatHelper recommended by the bot is a good way of doing things.

@JuliaRegistrator register

**Comment by mkborregaard** [comment]
Yes. @daschw is compathelper not activated for this repo? It is for most other JuliaPlots repos I think.
