### ISSUE TITLE
node shape looks incorrect with GR

### ISSUE THREAD

**Issue by Roger-luo** [JuliaPlots/GraphRecipes.jl#90]
somehow I cannot reproduce the AST plot, and got this

![image](https://user-images.githubusercontent.com/8445510/72941165-4d28af00-3d3e-11ea-8450-b91a26104351.png)

with the default backend GR, but it seems fine with pyplot just with different colors.

**Comment by JackDevine** [comment]
Currently, everything on the readme is done on the master branch (where GR and PyPlot give the same results).

Once I tag the new release (#87 ), this issue will be fixed.

In the future, we should probably have "stable" and "latest" docs like everybody else. Sorry about all of the confusion...

**Comment by JackDevine** [comment]
@Roger-luo this should be fixed.

Could you please update to the latest GraphRecipes and let me know whether you still have the problem?

**Comment by Roger-luo** [comment]
Thanks! it looks correct now!

![image](https://user-images.githubusercontent.com/8445510/73597810-30d70000-44fe-11ea-8398-bb6bd839b69f.png)
