### ISSUE TITLE
Choose node locations

### ISSUE THREAD

**Issue by jpp46** [JuliaPlots/GraphRecipes.jl#92]
I cannot seem to find a way to force nodes to be in a specific location. I don't know the best way to do this but for instance if the size of my plot is size=(100, 100) I would like to pass a list or dictionary with the x,y position of the center of a node.

For example:
graphplot(g, names=1:5, position=[(0, 0), (10, 10),...,(20, 50)], size=(100, 100))
would put node 1 on the origin and node 2 at position (10, 10) and the last node at (20, 50).

**Comment by mkborregaard** [comment]
why would you need the graph layout at all then? Can't you just use `scatter` and `path` to achieve that?

**Comment by jpp46** [comment]
Yes, I realize this could be done manually, but then I could say the same thing about all of the graphs, why have this package at all? Just draw the nodes manually, and the paths, etc.

**Comment by mkborregaard** [comment]
Well one of the reasons is to calculate the graph layouts.

**Comment by mkborregaard** [comment]
Are you trying to achieve something in particular? If you give a bit of information it might not be too difficult to implement. But your response is not really not that helpful in understanding your use case and requirements (which was the purpose of my question).

**Comment by jpp46** [comment]
Never mind I found you can just override just like I want to with,

graphplot(g, x=x, y=y)

where x is the x coordinates of your nodes and y the y coordinates.
I guess really all this package needs is documentation. So I am closing this issue.

**Comment by mkborregaard** [comment]
Haha yes that's proven by the fact that I did not know that

**Comment by JackDevine** [comment]
Yeah, that feature (and many others) definitely needs to be documented. It is quite useful to quickly test out custom layouts. Also, setting a custom layout can be a nice way to create a flow chart, as pointed out on discourse.

I am working on a commit that will make custom layouts with small limits in one direction still look fine.

After that I will do some documentation, I think that a lot of confusion from users is quite understandable given the amount of documentation.
